services:
  
  react-app:
    build: ./frontend
    container_name: frontend_conatainer
    networks:
      - mern-net
  
  api-server:
    build:
      context: ./backend
    container_name: backend_conatainer
    networks:
      - mern-net
    depends_on:
      - mongo
  
  mongo:
    image: mongo:8.0.1-noble
    container_name: mongo_conatainer
    ports:
      - "27017:27017"
    networks:
      - mern-net
    volumes:
      - mongo-data:/data/db
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_conatainer
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - react-app
      - api-server  
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mern-net
    
  certbot:
    image: certbot/certbot
    container_name: certbot_container
    depends_on:
      - nginx
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --agree-tos --no-eff-email -d mesto.paveldev.ru

networks:
  mern-net:
    driver: bridge
volumes:
  mongo-data:
    driver: local
