version: "3"
services:
  # react-app:
  #   build: ./frontend
  #   image: react-app
  #   stdin_open: true
  #   ports: 
  #     - "3000:3000"
  #   networks:
  #     - mern-app
  api-server:
    build: ./backend
    image: api-server
    ports:
      # - "3001:3000"
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:8.0.1-noble
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   networks:
  #     - mern-app
  #   depends_on:
  #     - react-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local