services:
  
  react-app:
    build: ./frontend
    container_name: frontend_conatainer
    # image: react-app
    # image: energetikk/react-app
    # stdin_open: true
    # ports: 
    #   - "3000:3000"
    networks:
      - mern-net
  
  api-server:
    build:
      context: ./backend
    # image: api-server
    # image: energetikk/api-server
    container_name: backend_conatainer
    # ports:
    #   - "3001:3000"
      # - "3000:3000"
    networks:
      - mern-net
    depends_on:
      - mongo
  
  mongo:
    image: mongo:8.0.1-noble
    container_name: mongo_conatainer
    ports:
      - "27017:27017"
    networks:
      - mern-net
    volumes:
      - mongo-data:/data/db
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_conatainer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
      - api-server  
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mern-net
    

networks:
  mern-net:
    driver: bridge
volumes:
  mongo-data:
    driver: local
